#ifndef KSTATUS_H
#define KSTATUS_H

#include <stdint.h>

typedef int32_t KSTATUS;

#define KSTATUS_SUCCESS ((KSTATUS)0)
#define KSTATUS_NOT_IMPLEMENTED ((KSTATUS)-1)
#define KSTATUS_INVALID_PARAMETER ((KSTATUS)-2)
#define KSTATUS_INIT_FAILED ((KSTATUS)-3)
#define KSTATUS_NOT_FOUND ((KSTATUS)-4)
#define KSTATUS_ALREADY_INITIALIZED ((KSTATUS)-5)
#define KSTATUS_ACCESS_DENIED ((KSTATUS)-6)
#define KSTATUS_WOULD_BLOCK ((KSTATUS)-7)

#endif /* KSTATUS_H */
